### ISSUE TITLE
Glitched visuals in entities

### ISSUE THREAD

**Issue by style-nine** [minetest-mods/drawers#35]
Linux Minetest 5.1.0-dev-39c54e1
GeForce GTX 1050
nvidia driver 390.116-0ubuntu0.18.04.1

At a distance the drawer entities exhibit what appears to be z-fighting. See the attached image for an example. I've found that changing the node box (in api.lua) clears up the issue, but there might be a better way to solve this.

`drawers.node_box_simple = {
	{-0.5, -0.5, -0.42, 0.5, 0.5, 0.5},
	{-0.5, -0.5, -0.5, -0.42, 0.5, -0.42},
	{0.42, -0.5, -0.5, 0.5, 0.5, -0.42},
	{-0.42, 0.42, -0.5, 0.42, 0.5, -0.42},
	{-0.42, -0.5, -0.5, 0.42, -0.42, -0.42},
}
`
![drawerbug](https://user-images.githubusercontent.com/41269111/59941681-cf10cc80-942b-11e9-8e28-2c01eb02acb7.jpg)

**Comment by thomasrudin** [comment]
this should be fixed with #36

**Comment by style-nine** [comment]
That actually does not fix it. That actually makes the problem worse. The value needs to be lower, not higher.

**Comment by style-nine** [comment]
Okay, this works but you have to completely remove and replace the old drawers.
